create table "LADDER"
(
    "ID" RAW(16) NOT NULL,
    "ACCOUNT_ID" VARCHAR(32) NULL,
    "INSTRUMENT_ID" RAW(16) NOT NULL,
    "STEP_QUANTITY" NUMBER(16) NOT NULL,
    "STEP_INTERVAL" NUMBER(16) NOT NULL,
    "DIRECTION" VARCHAR(16) NOT NULL,
    "TYPE" VARCHAR(16) NOT NULL,
    "START_TIME" TIMESTAMP NOT NULL,
    "END_TIME" TIMESTAMP NOT NULL,
    "FIRST_PRICE" NUMBER(16,2) NOT NULL,
    "LAST_PRICE" NUMBER(16,2) NOT NULL,
    "STATUS" VARCHAR(16) NOT NULL
);

alter table "LADDER" add constraint "LADDER_PK" primary key ("ID");