create table "LADDER"
(
    "ID" RAW(16) NOT NULL,
    "ACCOUNT_ID" VARCHAR(32) NULL,
    "INSTRUMENT_ID" RAW(16) NOT NULL,
    "STEP_QUANTITY" NUMBER(16) NOT NULL,
    "STEP_INTERVAL" VARCHAR(16) NOT NULL,
    "TYPE" VARCHAR(16) NOT NULL,
    "DIRECTION" VARCHAR(16) NOT NULL,
    "STATUS" VARCHAR(16) NOT NULL,
    "START_TIME" TIMESTAMP NOT NULL,
    "END_TIME" TIMESTAMP NOT NULL,

    "FIRST_ORDER_PRICE" NUMBER(16,2),
    "FIRST_ORDER_ON" TIMESTAMP,
    "LAST_ORDER_PRICE" NUMBER(16,2),
    "LAST_ORDER_ON" TIMESTAMP
);

alter table "LADDER" add constraint "LADDER_PK" primary key ("ID");